---
abstract: 'Access SmartyStreet API'
author:
  - 'binary.com <BINARY@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::CheckDeps: '0.010'
  Test::FailWarnings: '0'
  Test::Fatal: '0'
  Test::More: '0.94'
  Test::Warn: '0'
  perl: '5.014000'
configure_requires:
  ExtUtils::MakeMaker: '6.64'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.012, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: WebService-Async-SmartyStreets
requires:
  Future::AsyncAwait: '0.21'
  IO::Async::SSL: '0'
  Net::Async::HTTP: '0.44'
  indirect: '0'
  mro: '0'
  parent: '0'
resources:
  bugtracker: https://github.com/binary-com/perl-WebService-Async-SmartyStreets/issues
  repository: git://github.com/binary-com/perl-WebService-Async-SmartyStreets.git
version: '0.001'
x_generated_by_perl: v5.26.2
x_serialization_backend: 'YAML::Tiny version 1.66'
